# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=200)),
                ('businees_name', models.CharField(max_length=200)),
                ('business_address', models.CharField(max_length=200)),
                ('businees_telephone', models.CharField(max_length=11)),
                ('businees_fax', models.CharField(max_length=11)),
                ('businees_email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question_response', models.CharField(max_length=200)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miafd.Business')),
            ],
        ),
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_reviewer', models.CharField(max_length=30)),
                ('comment_publish_date', models.DateTimeField(verbose_name='date published')),
                ('comment_text', models.CharField(max_length=250)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miafd.Business')),
            ],
        ),
    ]
